// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'fr-FR',
  supportedLanguages: ['fr-FR'],
  helloFreshGW: '/hello-fresh',
  helloFreshFE: '/hello-fe',
  colruytGW: '/colruyt',
  firebase: {
    apiKey: 'AIzaSyDFiaYo8GKshR4h11wj1Q6h5XQWilP9zS8',
    authDomain: 'fresh-and-go.firebaseapp.com',
    databaseURL: 'https://fresh-and-go.firebaseio.com',
    projectId: 'fresh-and-go',
    storageBucket: 'fresh-and-go.appspot.com',
    messagingSenderId: '136926805345',
    measurementId: 'G-GL1DHHQZXL',
    appId: '1:136926805345:web:7a44a3737f34f124531920',
  },
};
